package com.pccw.mobile.sip;

import android.net.Uri;

public class Constants {
    public static final String AUTH_GET_IMSI_URL = "https://sip.pccwmobile.com/voip02/authGetimsi.do";
    public static final String CALL_FORWARD_URL = "https://sip.pccwmobile.com/voip02/callforward.do";
    public static final String CHAT_TYPE_GROUP = "group";
    public static final String CHAT_TYPE_INDIVIDUAL = "individual";
    public static final String CHECK_LOCATION_URL = "https://sip.pccwmobile.com/voip02/checkLocation.do";
    public static final String CHECK_PREPAID_BALANCE_LOWER_THAN_THREAHOLD_TRUE = "true";
    public static final String CHECK_PREPAID_BALANCE_URL = "https://sip.pccwmobile.com/voip02/checkPrepaidBalance.do";
    public static final String CHECK_SMS_DELIVERY_STATUS_URL = "https://sip.pccwmobile.com/voip02/smsstatus.do";
    public static final String CHECK_VERSION_URL = "http://sip.pccwmobile.com/voip02/version.do";
    public static final String CONFERENCE_ROOM_CALLER_ID = "conference@pccwone.com";
    public static final String CONFERENCE_ROOM_CALLER_PREFIX = "conference@";
    public static final String CONFIRM_NUMBER_TYPE = "numberType";
    public static final String CONFIRM_REGISTRATION_URL = "https://sip.pccwmobile.com/voip02/confirmRegistration.do";
    public static final String CONFIRM_REG_ACTIVATION_FIRST_TIME = "True";
    public static final String CONFIRM_REG_IS_FREE_TRIAL_KEY = "isFreeTrial";
    public static final String CONFIRM_REG_MSISDN_KEY = "msisdn";
    public static final String CSL_PREPAID_TOPUP_NUM = "179179";
    public static final String ConversationParticipantItemService = "ConversationParticipantItemService";
    public static final String FACEBOOK_SHARE_EN_URL = "https://sip.pccwmobile.com/voip02/sharing/fbPost_en.xml";
    public static final String FACEBOOK_SHARE_ZH_URL = "https://sip.pccwmobile.com/voip02/sharing/fbPost_ch.xml";
    public static final long FORCE_CHECK_VERSION_TIME = 7200000;
    public static final String GET_CALLEE_STATUS_URL = "https://sip.pccwmobile.com/voip02/getCalleeStatus.do";
    public static final String GET_LANG_ENGLISH = "en";
    public static final String GET_LANG_TRADITIONAL_CHINESE = "zh_HK";
    public static final String GET_MSISDN_BY_IMSI_URL = "https://sip.pccwmobile.com/voip02/getDImsi.do";
    public static final String GET_NUMBER_INFO_ALLOW_RS_TRUE = "true";
    public static final String GET_NUMBER_INFO_BRAND_1010 = "1010";
    public static final String GET_NUMBER_INFO_BRAND_NEWWORLD = "nw";
    public static final String GET_NUMBER_INFO_BRAND_ONE2FREE = "one2free";
    public static final String GET_NUMBER_INFO_CLASS_CSL_PREPAID = "csl";
    public static final String GET_NUMBER_INFO_CLASS_HELLO_PREPAID = "Hello";
    public static final String GET_NUMBER_INFO_CLASS_NORMAL_PREPAID = "Normal";
    public static final String GET_NUMBER_INFO_FREE_TRIAL_PROMOTION_ACTIVE = "Available";
    public static final String GET_NUMBER_INFO_IS_FREE_TRIAL_NUM = "true";
    public static final String GET_NUMBER_INFO_IS_PURCHASED_VIRTUAL_NUMBER = "true";
    public static final String GET_NUMBER_INFO_OPERATOR_CSL = "csl";
    public static final String GET_NUMBER_INFO_OPERATOR_PCCW = "hkt";
    public static final String GET_NUMBER_INFO_REGISTERED_FREE_TRIAL = "true";
    public static final String GET_NUMBER_INFO_SIMTYPE_2N = "2N";
    public static final String GET_NUMBER_INFO_SIMTYPE_POSTPAID = "postpaid";
    public static final String GET_NUMBER_INFO_SIMTYPE_PREPAID = "prepaid";
    public static final String GET_NUMBER_INFO_STATUS_ACTIVE = "active";
    public static final String GET_NUMBER_INFO_STATUS_IDLE = "idle";
    public static final String GET_NUMBER_INFO_VIRTUAL_NUMBER_STATUS_ACTIVE = "active";
    public static final String GET_NUMBER_TYPE_URL = "https://sip.pccwmobile.com/voip02/getNumberType.do";
    public static final String GET_SMS_TYPE = "https://sip.pccwmobile.com/voip02/getSMSType.do";
    public static final String GET_VIRTUAL_NUMBER_IS_PROMOTION_KEY = "isInPromotionPeriod";
    public static final String GET_VIRTUAL_NUMBER_URL_KEY = "url";
    public static final int HEARTBEAT_NORMAL_INTERVAL = 30000;
    public static final int HEARTBEAT_RETRY_INTERVAL = 10000;
    public static final int HEARTBEAT_RETRY_INTERVAL_MIN = 100;
    public static final int HEARTBEAT_RETRY_MAX = 2;
    public static final String HEARTBEAT_URL = "https://sip.pccwmobile.com/voip02/heartbeat.do";
    public static final String HELLO_PREPAID_TOPUP_NUM = "1833808";
    public static final String HKT_HOTLINE_HTML_URL_CH = "http://sip.pccwmobile.com/voip02/message/toll_free_numbers_ch.html";
    public static final String HKT_HOTLINE_HTML_URL_EN = "http://sip.pccwmobile.com/voip02/message/toll_free_numbers_en.html";
    public static final String HKT_TOLL_FREE_NUMBER = "+85228888333";
    public static final String HTTPS_LOGIN_PATH = "https://sip.pccwmobile.com/voip02/login.do";
    public static final String IM_IMSIDN_VERIFY_URL = "https://sip.pccwmobile.com/voip02/imsiDVerify.do";
    public static final String IM_REGISTRATION_URL = "https://sip.pccwmobile.com/kkim/api/registration.do";
    public static final String INTENT_ALERT_AUTOLOGIN_PROCESSING = "com.pccw.mobile.sip.intent.autologinprocessing";
    public static final String INTENT_ALERT_CALLFORWARD_SUCCEED = "com.pccw.mobile.sip.intent.callforwardsucceed";
    public static final String INTENT_ALERT_LOGIN_DISCONNECTED = "com.pccw.mobile.sip.intent.logindisconnected";
    public static final String INTENT_ALERT_LOGIN_DISCONNECTED_EXTRA_NEED_SHOW_MESSAGE = "NEED_SHOW_MESSAGE";
    public static final String INTENT_ALERT_LOGIN_DISCONNECTING = "com.pccw.mobile.sip.intent.logindisconnecting";
    public static final String INTENT_ALERT_LOGIN_ERROR = "com.pccw.mobile.sip.intent.loginerror";
    public static final String INTENT_ALERT_LOGIN_FINISHED = "com.pccw.mobile.sip.intent.loginfinished";
    public static final String INTENT_ALERT_LOGIN_PASSWORD_ERROR = "com.pccw.mobile.sip.intent.loginpassworderror";
    public static final String INTENT_ALERT_LOGIN_WARNING = "com.pccw.mobile.sip.intent.loginwarning";
    public static final String INTENT_ALERT_RELOGIN_PROCESSING = "com.pccw.mobile.sip.intent.reloginprocessing";
    public static final String INTENT_ALERT_SYNC_IMUSER_FINISH = "com.pccw.mobile.sip.intent.syncimuserfinish";
    public static final String INTENT_DIAL_ACTION = "com.pccw.mobile.sip.service.intent.dial";
    public static final String INTENT_MORE_ACTION = "com.pccw.mobile.sip.service.intent.more";
    public static final String INTENT_PREFIX = "com.pccw.mobile.sip";
    public static final String INTERT_ALERT_DAYPASS = "com.pccw.mobile.sip.intent.daypass";
    public static final String LOG_TAG = "PCCW_MOBILE_SIP";
    public static final String LOG_TAG_DEV = "testing";
    public static final int MAX_SIP_FAIL_ATTEMPTS = 1;
    public static final int MISSED_CALL_NOTIFICATION = 3;
    public static final String NETWORK_SHARE_PREF = "NETWORK_SHARE_PREF";
    public static final String NORMAL_PREPAID_TOPUP_NUM = "1833803";
    public static final int POSTPAID_MAX_CALL = 3;
    public static final int PREPAID_MAX_CALL = 1;
    public static final String PREPAID_TOPUP_URL = "https://sip.pccwmobile.com/voip02/prepaidTopUp.do?msisdn=MSISDN_VALUE&r=R_VALUE";
    public static final String ROAM_SAVE_AUTHEN_URL = "https://sip.pccwmobile.com/roamSaveAuthen02/RoamSaveAuthen";
    public static final String SEND_SMS_URL = "https://sip.pccwmobile.com/voip02/deliverSMS.do";
    public static final String SHOW_DAYPASS_MESSAGE = "SHOW_DAYPASS_MESSAGE";
    public static final String SMS_INVITE_API_URL = "https://sip.pccwmobile.com/voip02/sendSharingSms.do";
    public static final String SMS_INVITE_EN_URL = "https://sip.pccwmobile.com/voip02/sharing/smsSharingEn.xml";
    public static final String SMS_INVITE_ZH_URL = "https://sip.pccwmobile.com/voip02/sharing/smsSharingCh.xml";
    public static final long SPLASH_SCREEN_MIN_SHOW_TIME = 1000;
    public static final String T_AND_C_RECORD_ACCEPT_URL = "https://sip.pccwmobile.com/voip02/acceptTandC.do";
    public static final Uri URL_PCCW_MOBILE = Uri.parse("http://pccwmobile.com");
    public static final String VOICE_MAIL_NUMBER = "*988";
    public static final String VOICE_MAIL_NUMBER_CSL = "*988";
    public static final boolean bypassTargetDay = false;
    public static final boolean canShowImsi = false;
    public static final int contactBatchLimit = 50;
    public static String domainName = "imxmpp.pccw-hkt.com";
    public static final String echoServerHost = "echoServerHost";
    public static final String echoServerHost1 = "echoServerHost1";
    public static final String echoServerHost2 = "echoServerHost2";
    public static final String echoServerHostTest = "echoServerHostTest";
    public static final boolean enableAutoCodecSelection = true;
    public static final boolean hasKKUserSyncFeature = false;
    public static final boolean isByPassHeartBeatServerErrorResp = false;
    public static final int minCallCountDuration = 60;
    public static int mockACC = 0;
    public static final boolean mockHttpsLogin = false;
    public static int mockOrientationMode = 1;
    public static final boolean mockVideoCallACC = false;
    public static final boolean release = true;
    public static final boolean shouldIgnoreNonPccwIdd = true;
    public static final boolean showProdFAQ = true;
    public static final boolean showProdUserGuide = true;
    public static final int targetDayInterval = 14;
    public static final int targetNumOfCall = 5;
    public static final String validEchoServerHost = "validEchoServerHost";

    public class TransportConstants {
        public static final byte TCP_SOCK = 1;
        public static final byte UDP_SOCK = 2;
        public static final byte UND_SOCK = 0;

        public TransportConstants() {
        }
    }
}
